name: 'Scan Tanzu Packages'
on:
  push:
    branches:
      - '**'
#on:
#  schedule:
#    # * is a special character in YAML so you have to quote this string
#    - cron: '*/5 * * * *'
jobs:
  scan-images:
    runs-on: ubuntu-latest
    steps:
      - name: "Run scan tanzu packages script"
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy
          mkdir local-bin/
          curl -L https://carvel.dev/install.sh | K14SIO_INSTALL_BIN_DIR=local-bin bash
          export PATH=$PWD/local-bin/:$PATH
          imgpkg version
          imgpkg pull --recursive -b projects.registry.vmware.com/tce/main:latest -o /tmp/tce-main
          cat /tmp/tce-main/.imgpkg/images.yml | grep "image:" | cut -d ':' -f 2- | cut -d '@' -f 2 > package-images.txt
          echo "All packages identified"
          sed 's/:/-/g' package-images.txt > directories.txt
          dirs=directories.txt
          rm -f images.txt
          touch images.txt
          while IFS= read -r path
          do
            cat /tmp/tce-main/.imgpkg/bundles/$path/.imgpkg/images.yml | grep "image:" | cut -d ':' -f 2- >> images.txt
          done < "$dirs"
          images=images.txt
          echo "All images identified"
          sed -i '' -e '$a\' images.txt
          rm -f scan-output.txt
          touch scan-output.txt
          counter=1
          mkdir -p scan-results
          while IFS= read -r image
          do
            trivy image --format sarif -o "./scan-results/report-$counter.sarif" --ignore-unfixed --severity CRITICAL $image
            counter=$((counter+1))
          done < "$images"
        shell: bash
      - name: "Upload SARIF file"
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ./.github/workflows/scan-results
          category: image-vulnerabilities