name: 'Security - Scan Tanzu Packages'
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'
jobs:
  get-all-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Identify all images
        run: |
          mkdir local-bin/
          curl -L https://carvel.dev/install.sh | K14SIO_INSTALL_BIN_DIR=local-bin bash
          export PATH=$PWD/local-bin/:$PATH
          imgpkg version
          imgpkg pull --recursive -b projects.registry.vmware.com/tce/main:latest -o /tmp/tce-main
          cat /tmp/tce-main/.imgpkg/images.yml | grep "image:" | cut -d ':' -f 2- | cut -d '@' -f 2 > package-images.txt
          echo "All packages identified"
          sed 's/:/-/g' package-images.txt > directories.txt
          dirs=directories.txt
          mkdir -p images-list
          counter=1
          number=1
          while IFS= read -r path
          do
            touch ./images-list/images-$number.txt
            cat /tmp/tce-main/.imgpkg/bundles/$path/.imgpkg/images.yml | grep "image:" | cut -d ':' -f 2- >> ./images-list/images-$number.txt
            if [ $(( $counter % 12 )) -eq 0 ] ; then
              number=$((number+1))
            fi
            counter=$((counter+1))
          done < "$dirs"
          echo "All images identified"
      - name: Upload Images list
        uses: actions/upload-artifact@v2
        with:
          name: images-list
          path: images-list/

  scan-images:
    runs-on: ubuntu-latest
    needs: get-all-images
    strategy:
      matrix:
        sarif-directory: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: images-list
      - name: "Run scan tanzu packages script"
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy
#          images=images.txt
          sed -i -e '$a\' images-${{ matrix.sarif-directory }}
          rm -f scan-output.txt
          touch scan-output.txt
          counter=1
#          for i in {1..10}
#          do
#            mkdir -p scan-results-$i
#          done
          #Divide the scan results into 10 runs each, to avoid hitting code scanning limits. Max == 15
          while IFS= read -r images-${{ matrix.sarif-directory }}
          do
            trivy --debug image --timeout 15m --format sarif -o "./scan-results-$/report-$counter.sarif" --ignore-unfixed --severity CRITICAL $image
            echo "Image name: " $image
            counter=$((counter+1))
          done < "$images"
          echo $pwd
        shell: bash
      - name: "Upload SARIF file"
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: scan-results-${{ matrix.sarif-directory }}
          category: scan-results-${{ matrix.sarif-directory }}
          wait-for-processing: true
